- name: MariaDB 削除
  yum: name=mariadb-libs state=removed

- name:  レポジトリの登録
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    state: present

- name: mysqld のインストール
  yum:
    name: "{{ item }}"
    enablerepo: mysql56-community
    disablerepo: mysql57-community
    state: present
  with_items:
    - mysql-community-server
    
- name: MySQL5.6 起動
  service: name=mysqld state=started enabled=yes

- name: Configure MySQL
  shell:
    mysqladmin -u root password password;